services:
  backend:
    image: ruby:3.2.3-slim
    working_dir: /rails
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/rails
      - backend_bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    networks:
      - app-network
    command: >
      bash -c "
        apt-get update -qq &&
        apt-get install -y build-essential git pkg-config sqlite3 firefox-esr ca-certificates curl &&
        update-ca-certificates &&
        bundle install &&
        bundle exec rails db:prepare &&
        bundle exec rails server -b 0.0.0.0 -p 3001
      "

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE=http://backend:3001/api/v1
    networks:
      - app-network
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0
      "
    depends_on:
      - backend

volumes:
  backend_bundle:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge