services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/rails
      - backend_bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE=http://backend:3001/api/v1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

volumes:
  backend_bundle:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge